
import "./globals.css";
import { CssBaseline, ThemeProvider } from "@mui/material";
import theme from "@/theme/theme";

export const metadata = {
  title: "Chat App",
  description: "Generated by Chat app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
         <ThemeProvider theme={theme}>
          <CssBaseline /> {/* Reset CSS to match theme */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
